[package]
name = "xxx"
version = "0.1.0"
edition = "2025"

[dependencies]
lang-c = "0.15"
cranelift = "0.102"
cranelift-module = "0.102"
cranelift-object = "0.102"
target-lexicon = "0.12"
anyhow = "1.0"
